// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://grtuwjxwutwqfdbpehfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZnluZmVwaXJ6dGJjeWJxZmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNTc1MjYsImV4cCI6MjA4OTYzMzUyNn0.KiPncVzIhvMCF8iy4fESV7gPzvrX43nmMIQX6YM9Ivk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);