// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://grtuwjxwutwqfdbpehfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yR12157HS_hHZW5H9cypxA_m_IpVJP-";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);