import { BrowserRouter, Routes, Route, Outlet } from "react-router-dom";
import { ClerkProvider, SignedIn } from "@clerk/clerk-react";
import { AuthProvider } from "./contexts/AuthContext";
import Layout from "./components/Layout";
import Index from "./pages/Index";
import Login from "./pages/Login";
import Register from "./pages/Register";
import ChooseRole from "./pages/ChooseRole";
import AuthSync from "./components/AuthSync";
import RoleProtectedRoute from "./components/RoleProtectedRoute";
import TruckerDashboard from "./pages/trucker/Dashboard";
import ShipperDashboard from "./pages/shipper/Dashboard";
import PostTrip from "./pages/trucker/PostTrip";
import MyTrips from "./pages/trucker/MyTrips";
import EditTrip from "./pages/trucker/EditTrip";
import MyRequests from "./pages/trucker/MyRequests";
import TruckerHistory from "./pages/TruckerHistory";
import PostShipments from "./pages/shipper/PostShipments";
import MyShipments from "./pages/shipper/MyShipments";
import EditShipment from "./pages/shipper/EditShipment";
import ShipmentDetail from "./pages/shipper/ShipmentDetail";
import ShipperHistory from "./pages/ShipperHistory";
import TripDetail from "./pages/TripDetail";
import Chat from "./pages/Chat";
import ChatList from "./pages/ChatList";
import Profile from "./pages/Profile";
import NotFound from "./pages/NotFound";
import BrowseShipments from "./pages/trucker/BrowseShipments";
import "./globals.css";