// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yrmawmjyjmqotnygcskf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybWF3bWp5am1xb3RueWdjc2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNzAwMDMsImV4cCI6MjA4OTY0NjAwM30.a1toJulWYTkBKd4yO5UfpfOzfmHAKQdKW7BScno4124";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);